# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    container_name: eduschedule_db
    environment:
      POSTGRES_DB: eduschedule
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: